// REQUESTS FOR SONGS

### GET ALL SONGS
GET http://localhost:3456/songs

### GET SONG BY ID
GET http://localhost:3456/songs/6985c5fc6d0dd8d64dd98556

### CREATE SONG
POST http://localhost:3456/songs
Content-Type: application/json

{
    "title": "Hide in Shade",
    "artists": ["Zeal & Ardor"],
    "album": "GREIF",
    "genres": ["Black Metal", "Gospel"],
    "releaseDate": "2021-01-01",
    "duration": 210
}

### UPDATE SONG
PATCH http://localhost:3456/songs/6985c5fc6d0dd8d64dd98556
Content-Type: application/json

{
    "title": "Hide in Shade",
    "artists": ["Zeal & Ardor"],
    "album": "GREIF",
    "genres": ["Black Metal", "Gospel"],
    "releaseDate": "2021-01-01",
    "duration": 210
}
### REPLACE SONG
PUT http://localhost:3456/songs/6985c5fc6d0dd8d64dd98556
Content-Type: application/json

{
    "title": "Hide in Shade",
    "artists": ["Zeal & Ardor"],
    "album": "GREIF",
    "genres": ["Black Metal", "Gospel"],
    "releaseDate": "2021-01-01",
    "duration": 210
}
### DELETE SONG
DELETE http://localhost:3456/songs/6985c5fc6d0dd8d64dd98556

